# Generated by Django 5.0 on 2023-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='learitlessons', max_length=255),
        ),
    ]
